In [2]:
# Import required libraries
import numpy as np

In [3]:
# Define a 2D array
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[11, 12],
       [13, 14]])

In [6]:
# dot Product
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [7]:
a.dot(b)

array([[37, 40],
       [85, 92]])

In [8]:
# Verify output
[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

[[37, 40], [85, 92]]

In [9]:
a @ np.ones(2)  # equal to a.dot(np.ones(2))

array([3., 7.])

In [14]:
# vdot 
print(np.vdot(a,b))
print(np.dot(a,b))

130
[[37 40]
 [85 92]]


In [15]:
np.vdot(b, a)

130

In [16]:
# Verify output
1*11 + 2*12 + 3*13 + 4*14

130

In [17]:
from numpy.linalg import multi_dot

In [18]:
w = np.random.random((10000, 100))
x = np.random.random((100, 1000))
y = np.random.random((1000, 5))
z = np.random.random((5, 333))

In [19]:
# the actual dot multiplication
out_1 = multi_dot([w, x, y, z])
out_1

array([[34559.8181365 , 35886.63742415, 32864.95672185, ...,
        33094.04541464, 14991.07386548, 29907.51722609],
       [36889.17551871, 38301.37853411, 35067.22351905, ...,
        35315.57292085, 16005.94574175, 31914.05594761],
       [27921.31922885, 28994.5204836 , 26548.136376  , ...,
        26741.14509798, 12111.74198529, 24158.47882107],
       ...,
       [35369.79132547, 36732.6557209 , 33609.46650729, ...,
        33858.22683863, 15351.163903  , 30592.48268694],
       [33926.04595231, 35229.95711392, 32252.49725679, ...,
        32484.55418799, 14719.48300879, 29352.63501426],
       [32632.65495281, 33885.79639559, 31018.09534861, ...,
        31246.64604421, 14161.26444006, 28231.08180924]])

In [20]:
# output shape
out_1.shape

(10000, 333)

In [21]:
# Same as above
out_2 = np.dot(np.dot(np.dot(w, x), y), z)
out_2.shape

(10000, 333)

In [22]:
# Same as above
out_3 = w.dot(x).dot(y).dot(z)
out_3.shape

(10000, 333)

In [23]:
# Import Linear Algebra module from NumPy
from numpy import linalg as LA

In [24]:
dia = np.diag((2, 3, 4))
dia

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [25]:
# Derive eigen values and vectors
e_val,e_vec = LA.eig(dia)

In [26]:
# Eigen Values
e_val

array([2., 3., 4.])

In [27]:
# Eigne Vectors
e_vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# let A be the 2x2 square matrix
A = np.array([[3,-4], [2,-6]])

In [29]:
LA.eig(A) # calculates the eigen-values and eigen-vectors

(array([ 2., -5.]), array([[0.9701425 , 0.4472136 ],
        [0.24253563, 0.89442719]]))

In [36]:
print(A)
print(LA.det(A))# determinant of A

[[ 2  1 -2]
 [ 3  2  2]
 [ 5  4  3]]
-7.000000000000004


In [37]:
LA.inv(A) # inverse of A

array([[ 0.28571429,  1.57142857, -0.85714286],
       [-0.14285714, -2.28571429,  1.42857143],
       [-0.28571429,  0.42857143, -0.14285714]])

In [38]:
A = np.array([[2,1,-2], [3,2,2], [5,4,3]])
b = np.array([10,1,4])

In [39]:
A

array([[ 2,  1, -2],
       [ 3,  2,  2],
       [ 5,  4,  3]])

In [40]:
b

array([10,  1,  4])

In [41]:
x = LA.solve(A,b)
x

array([ 1.,  2., -3.])

In [63]:
print(np.dot(A,x))
print(b)
print(np.allclose(np.dot(A,x), b))

[10.  1.  4.]
[10  1  4]
True


In [43]:
LA.matrix_rank(A)

3

In [45]:
np.dot(A.T,A)#same as outer product of the matrix

array([[38, 28, 17],
       [28, 21, 14],
       [17, 14, 17]])

In [48]:
print(A)
print(np.outer(A,A))

[[ 2  1 -2]
 [ 3  2  2]
 [ 5  4  3]]
[[  4   2  -4   6   4   4  10   8   6]
 [  2   1  -2   3   2   2   5   4   3]
 [ -4  -2   4  -6  -4  -4 -10  -8  -6]
 [  6   3  -6   9   6   6  15  12   9]
 [  4   2  -4   6   4   4  10   8   6]
 [  4   2  -4   6   4   4  10   8   6]
 [ 10   5 -10  15  10  10  25  20  15]
 [  8   4  -8  12   8   8  20  16  12]
 [  6   3  -6   9   6   6  15  12   9]]


In [49]:
#https://en.wikipedia.org/wiki/Outer_product#:~:text=In%20linear%20algebra%2C%20the%20outer,outer%20product%20is%20a%20tensor.

In [53]:
B=np.arange(1,6,1)
print(B)

[1 2 3 4 5]


In [54]:
C=B.reshape(5,1)
print(C)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [55]:
C.shape

(5, 1)

In [59]:
D=C.flatten() #reduce one dimension
print(D.shape)

(5,)


In [62]:
E=D[:,np.newaxis] #add a new dimension
print(E.shape)

(5, 1)
