In [1]:
# Import required libraries
import numpy as np

In [2]:
# Check the version
np.__version__

'1.16.2'

In [3]:
#Array Creation
#Arrays from list
I=np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
I1=np.eye(3)
print(I1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Seed for reproducibility
np.random.seed(1)  

# 1D array
x1 = np.random.randint(10, size=5)  

# 2D array
x2 = np.random.randint(10, size=(2, 3))  

# 3D array
x3 = np.random.randint(10, size=(2, 3, 5)) 

In [7]:
print(x1)
print(x2)
print(x3)

[5 8 9 5 0]
[[0 1 7]
 [6 9 2]]
[[[4 5 2 4 2]
  [4 7 7 9 1]
  [7 0 6 9 9]]

 [[7 6 9 1 0]
  [1 8 8 3 9]
  [8 7 3 6 5]]]


In [8]:
print("The Array Attributes are:")
print("-"*25)
print(f"x3 ndim:      {x3.ndim}")
print(f"x3 shape:     {x3.shape}")
print(f"x3 size:      {x3.size}")
print(f"x3 dtype:     {x3.dtype}")
print(f"x3 itemsize:  {x3.itemsize}")
print(f"x3 nbytes:    {x3.nbytes}")

The Array Attributes are:
-------------------------
x3 ndim:      3
x3 shape:     (2, 3, 5)
x3 size:      30
x3 dtype:     int32
x3 itemsize:  4
x3 nbytes:    120


In [9]:
array=np.array([[0, 1, 7],
       [6, 9, 2]])
print(array)

[[0 1 7]
 [6 9 2]]


In [16]:
print(array[::-1,])

[[6 9 2]
 [0 1 7]]


In [15]:
print(array[:,::-1])

[[7 1 0]
 [2 9 6]]


In [17]:
print(array[::-1, ::-1])

[[2 9 6]
 [7 1 0]]


In [19]:
print(array.T)

[[0 6]
 [1 9]
 [7 2]]


In [22]:
print(array)
print(np.sort(array,axis=0))
print(np.sort(array,axis=1))

[[0 1 7]
 [6 9 2]]
[[0 1 2]
 [6 9 7]]
[[0 1 7]
 [2 6 9]]


In [27]:
print(array)
print(np.sort(array))
print(np.argsort(array))

[[0 1 7]
 [6 9 2]]
[[0 1 7]
 [2 6 9]]
[[0 1 2]
 [2 0 1]]


In [26]:
np.argsort(array) # Indices of the sorted elements

array([[0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [28]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
# Concatenate along the first axis
arr1=np.concatenate([arr, arr])
print(arr1)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [31]:
arr1[2,:]

array([1, 2, 3])

In [32]:
x = np.array([1, 2, 3])
arr = np.array([[9, 8, 7],
                 [6, 5, 4]])

# Vertically stack the arrays
np.vstack([x, arr])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [33]:
# Horizontally stack the arrays
y = np.array([[55],
              [55]])
np.hstack([arr, y])

array([[ 9,  8,  7, 55],
       [ 6,  5,  4, 55]])

In [34]:
x = np.arange(9)
x1, x2, x3 = np.split(x, 3)
print(x1, x2, x3)

[0 1 2] [3 4 5] [6 7 8]


In [35]:
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7 8]


In [36]:
# Vertically split the arrays
arr = np.arange(16).reshape((4, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
upper, lower = np.vsplit(arr, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
x = np.random.randn(10)
y = np.random.randn(10)
print(x)
print(y)

[-1.30486124 -0.38057504 -0.74362701 -0.43712177 -0.42645009  1.3814073
  0.09837051 -0.36945748 -1.27321995  1.0149868 ]
[-1.48105971 -0.28709989 -0.05682428 -0.78810511  0.06770979 -1.03890593
 -0.26367745  0.53825057  1.52826025  1.95667685]


In [39]:
print(np.mod(x,y))

[-1.30486124 -0.09347514 -0.00491135 -0.43712177  0.04751842 -0.69640455
 -0.16530693  0.16879309  0.2550403   1.0149868 ]


In [43]:
print(x%y)

[-1.30486124 -0.09347514 -0.00491135 -0.43712177  0.04751842 -0.69640455
 -0.16530693  0.16879309  0.2550403   1.0149868 ]


In [44]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [45]:
np.add.reduce(x)

15

In [48]:
y=0
for item in x:
    y=y+item
print(y)

15


In [49]:
# Store intermediate results
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [50]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [51]:
# Arithmetic operations
x = np.arange(5)

print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

x      = [0 1 2 3 4]
x + 5  = [5 6 7 8 9]
x - 5  = [-5 -4 -3 -2 -1]
x * 2  = [0 2 4 6 8]
x / 2  = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]


In [52]:
numbers = np.random.rand(100000)

In [57]:
numbers = np.random.rand(100000)
print(f'Mininum{np.min(numbers): .4f}, Maximim{np.max(numbers): .4f}')

Mininum 0.0000, Maximim 1.0000


In [58]:
# Shorter syntax to use
numbers.min(), numbers.max(), numbers.sum()

(6.737492946884416e-07, 0.9999809276713819, 49898.98784349377)

In [59]:
%timeit min(numbers)
%timeit np.min(numbers)
%timeit numbers.min()

5.89 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.4 µs ± 389 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
30 µs ± 661 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [65]:
%time min(numbers)

Wall time: 5.98 ms


6.737492946884416e-07

In [66]:
%time np.min(numbers)

Wall time: 0 ns


6.737492946884416e-07

In [67]:
%time numbers.min()

Wall time: 0 ns


6.737492946884416e-07

In [68]:
arr = np.random.random((3,4))
arr

array([[0.35748613, 0.87911957, 0.9121581 , 0.15423503],
       [0.14335867, 0.73791255, 0.22810775, 0.0990575 ],
       [0.37803911, 0.16119886, 0.90995683, 0.9421725 ]])

In [69]:
arr.sum()

5.902802604570376

In [70]:
# Aggregation across column
arr.sum(axis=0)

array([0.87888391, 1.77823098, 2.05022268, 1.19546503])

In [71]:
# Aggregation across rows
arr.sum(axis=1)

array([2.30299884, 1.20843647, 2.3913673 ])

In [72]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [73]:
# Less than
x < 3

array([ True,  True, False, False, False])

In [74]:
# Not equal 
x != 3

array([ True,  True, False,  True,  True])

In [75]:
# Count values less than 4
np.count_nonzero(x<4)

3

In [76]:
# Count values less than 4
np.sum(x<4)

3

In [77]:
# Are they any values > 8?
np.any(x>8)

False

In [78]:
# Are all values < 8?
np.all(x<8)

True

In [79]:
np.sum((x>2) & (x<5))

2

In [81]:
np.count_nonzero((x>2) & (x<5))

2

In [82]:
# Save input array with .npy extension
np.save('outfile', x)

In [83]:
# Save input array as a text file
np.savetxt('outfile.txt', x)

In [84]:
# Load and reconstruct array from outflie.npy
print(np.load('outfile.npy'))

[1 2 3 4 5]


In [85]:
# Load and reconstruct array from outflie.txt
print(np.loadtxt('outfile.txt'))

[1. 2. 3. 4. 5.]


In [86]:
a =np.load('outfile.npy')
print(a+a)

[ 2  4  6  8 10]


In [87]:
b=np.loadtxt('outfile.txt')
print(b+b)

[ 2.  4.  6.  8. 10.]
